### ISSUE TITLE
Add gcc support

### ISSUE THREAD

**Issue by dungwinux** [dungwinux/fpconsole#18]
- Add support for C/C++ language by adding gcc/g++ parameter

**Comment by cszach** [comment]
Let GCC be a standalone compiler. If you were to make FPConsole to compile C and C++ as well, the "FP" in "FPConsole" wouldn't be "Free Pascal", but "Fast Programming" (I don't know up to you). And then we would have to change a lot of stuffs in FPConsole's website.

**Comment by dungwinux** [comment]
I know it. That's what I want. Now I'm finding way to compile different languages.

**Comment by cszach** [comment]
So now you want to turn FPConsole to be able to compile different languages?

**Comment by dungwinux** [comment]
Yeah, since we skip the build number 1.4

**Comment by cszach** [comment]
Maybe by doing that we will have more customers. It's okay.

**Comment by dungwinux** [comment]
Ya done with #16 yet ?

**Comment by cszach** [comment]
Testing it.

**Comment by cszach** [comment]
Life is great and everything will be okay.

**Comment by dungwinux** [comment]
That's the name of one of Kotlin Presentation

**Comment by cszach** [comment]
We can use that as our motto, or our motivation.

**Comment by dungwinux** [comment]
Maybe, `-f` will detect the source automatically while `-fs` will detect the source by the extension or switch. This is just planning, nothing have been done.

**Comment by dungwinux** [comment]
Did you commit every change ? I can't compile the source from branch `feat/open-editor`

**Comment by cszach** [comment]
So, if a file is dzung.cpp and we use `-fs` it should initialize the compiler for C++?

**Comment by dungwinux** [comment]
Maybe

**Comment by dungwinux** [comment]
Merged with #25
